In [118]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import KBinsDiscretizer

In [54]:
data_df = pd.read_excel('test_Data.xlsx')

In [55]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14745 entries, 0 to 14744
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   ID               14745 non-null  int64         
 1   Frequency        14745 non-null  object        
 2   InstlmentMode    14745 non-null  object        
 3   LoanStatus       14745 non-null  object        
 4   PaymentMode      14745 non-null  object        
 5   BranchID         14745 non-null  int64         
 6   Area             14199 non-null  object        
 7   Tenure           14745 non-null  int64         
 8   AssetCost        14745 non-null  int64         
 9   AmountFinance    14745 non-null  float64       
 10  DisbursalAmount  14745 non-null  float64       
 11  EMI              14745 non-null  float64       
 12  DisbursalDate    14745 non-null  datetime64[ns]
 13  MaturityDAte     14745 non-null  datetime64[ns]
 14  AuthDate         14745 non-null  datet

In [56]:
data_df.dropna(inplace=True)

In [57]:
print('Minimum value for AGE:', data_df['AGE'].min())
print('Maximum value for AGE:', data_df['AGE'].max())

Minimum value for AGE: 18.0
Maximum value for AGE: 85.0


In [58]:
Age_Bins = KBinsDiscretizer(n_bins=8, encode='ordinal', strategy='quantile')

In [59]:
data_df['Age_Bins'] =Age_Bins.fit_transform(data_df['AGE'].values.reshape(-1,1)).astype(int)
print('Total count of unique bins:', data_df['Age_Bins'].nunique())
print('Unique values assigned to each bin:', data_df['Age_Bins'].unique())

Total count of unique bins: 8
Unique values assigned to each bin: [6 3 5 2 4 1 0 7]


In [60]:
data_df[data_df['Age_Bins'] == 5]['AGE'].unique()

array([48., 45., 47., 44., 46.])

#### We'll consider the feature 'Area' to perform the frequency encoding

In [61]:
data_df['Area'].nunique()

80

In [62]:
data_df['Area'].unique()

array(['GUNA', 'CUTTACK', 'BURDWAN', 'CHANDIGARH', 'JAIPUR', 'JALANDHAR',
       'KANPUR', 'KARNAL', 'DEHRADUN', 'UDAIPUR', 'NELLORE',
       'AHMEDABAD AMBAVADI', 'BARODA', 'PARBHANI', 'MIRYALGUDA', 'INDORE',
       'LUDHIANA FEROZ GANDHI MARKET', 'KOTA', 'AHMEDABAD CG ROAD',
       'BHUBANESHWAR', 'RAJKOT', 'BHOPAL', 'VIDISHA', 'JABALPUR',
       'RAIPUR', 'BILASPUR', 'DURGAPUR', 'LUDHIANA   RANI JHANSI ROAD',
       'LUCKNOW', 'BANGALORE LALBAGH', 'GULBARGA', 'HUBLI', 'MANGALORE',
       'HYDERABAD BEGUMPET', 'KARIMNAGAR', 'MYSORE', 'NIZAMABAD',
       'SINDHANUR', 'VIJAYAWADA', 'VISHAKHAPATNAM', 'AMRAVATI',
       'GANDHIDHAM', 'LATUR', 'SOLAPUR', 'NAGPUR', 'NASHIK',
       'PUNE APTE ROAD', 'AHMEDNAGAR', 'TUMKUR', 'TADEPALLIGUDEM',
       'RAJAHMUNDRY', 'AURANGABAD', 'NEW DELHI BARAKHAMBHA ROAD',
       'MANDSAUR', 'SILIGURI', 'AKOLA', 'SIRSA', 'HOSHANGABAD',
       'KOLHAPUR', 'PATNA', 'SIWAN', 'BIKANER', 'UJJAIN', 'REWARI',
       'HANUMANGARH', 'KANKER', 'RATLAM', 'GHAZIABAD', 

In [63]:
freq_enc = data_df.groupby('Area').size()/len(data_df)
data_df['freq_Area'] = data_df['Area'].map(freq_enc)

In [64]:
print('Total number of unique values after freq encoding:', data_df['freq_Area'].nunique())

Total number of unique values after freq encoding: 61


In [65]:
data_df['freq_Area'].unique()

array([2.10125511e-02, 8.60245381e-03, 7.68579890e-03, 1.55126216e-02,
       1.36087999e-02, 1.51600621e-02, 9.44859681e-03, 1.71343957e-02,
       4.68904245e-02, 3.83584826e-02, 2.82047666e-02, 5.07685799e-02,
       1.01537160e-02, 1.38908476e-02, 4.30122691e-02, 1.16274150e-01,
       1.09293471e-02, 1.31927796e-01, 7.05119165e-04, 1.77690030e-02,
       1.14934424e-02, 7.54477507e-03, 2.39740516e-02, 9.66013256e-03,
       8.03835848e-03, 2.82047666e-03, 1.19870258e-03, 3.94866732e-03,
       1.46664786e-02, 5.64095332e-04, 2.15061345e-02, 1.25511211e-02,
       8.24989423e-03, 2.82047666e-04, 2.17176703e-02, 1.33972641e-03,
       9.37808490e-03, 1.97433366e-03, 5.78197715e-03, 1.76279791e-03,
       1.24806092e-02, 8.67296573e-03, 7.19221548e-03, 3.17303624e-03,
       2.11535750e-04, 3.52559583e-04, 2.60894091e-03, 3.87815541e-03,
       1.90382175e-03, 4.49866027e-02, 9.16654915e-03, 3.59610774e-02,
       8.17938232e-03, 5.71146524e-03, 2.32689324e-03, 7.05119165e-05,
      

In [66]:
print('Number of unique values in the LoanStatus:', data_df['LoanStatus'].nunique())
print('Number of unique values in the Frequency:', data_df['Frequency'].nunique())

Number of unique values in the LoanStatus: 2
Number of unique values in the Frequency: 3


In [68]:
import category_encoders as catenc
from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()
data_df['LoanStatus'] = labelencoder.fit_transform(data_df['LoanStatus'])

targetenc = catenc.TargetEncoder(smoothing=1, min_samples_leaf=1)
data_df['freq_loan'] = targetenc.fit_transform(data_df['Frequency'], data_df['LoanStatus'])

In [69]:
data_df['freq_loan'].unique()

array([0.92183288, 0.70552561, 0.73538961])

In [70]:
pd.crosstab(data_df['LoanStatus'], data_df['Frequency'])

Frequency   Half Yearly  Monthly  Quatrly
LoanStatus                               
0                  2771      174      437
1                  7701     2052     1047

In [108]:
Loanstat0 = data_df[data_df['LoanStatus'] == 0].shape[0]
Loanstat1 = data_df[data_df['LoanStatus'] == 1].shape[0]

Loan_prop0 = Loanstat0/data_df.shape[0]
Loan_prop1 = Loanstat1/data_df.shape[0]

HY_total = data_df[(data_df['Frequency'] == 'Half Yearly')].shape[0]
HY_Freq0 = data_df[(data_df['LoanStatus'] == 0) & (data_df['Frequency'] == 'Half Yearly') ].shape[0]/HY_total
HY_Freq1 = data_df[(data_df['LoanStatus'] == 1) & (data_df['Frequency'] == 'Half Yearly') ].shape[0]/HY_total

Mon_total = data_df[data_df['Frequency'] == 'Monthly'].shape[0]
Mon_Freq0 = data_df[(data_df['LoanStatus'] == 0) & (data_df['Frequency'] == 'Monthly') ].shape[0]/Mon_total
Mon_Freq1 = data_df[(data_df['LoanStatus'] == 1) & (data_df['Frequency'] == 'Monthly') ].shape[0]/Mon_total

Qua_total = data_df[data_df['Frequency'] == 'Quatrly'].shape[0]
Qua_Freq0 = data_df[(data_df['LoanStatus'] == 0) & (data_df['Frequency'] == 'Quatrly') ].shape[0]/Qua_total
Qua_Freq1 = data_df[(data_df['LoanStatus'] == 1) & (data_df['Frequency'] == 'Quatrly') ].shape[0]/Qua_total

In [116]:
print('Loan proportion for 0:', Loan_prop0)
print('Loan proportion for 1:', Loan_prop1)

print('\nHalf_Yearly proprotion for 0:', HY_Freq0)
print('Half_Yearly proprotion for 1:', HY_Freq1)

print('\nMonthly proprotion for 0:', Mon_Freq0)
print('Monthly proprotion for 1:', Mon_Freq1)

print('\nQuaterly proprotion for 0:', Qua_Freq0)
print('Quaterly proprotion for 1:', Qua_Freq1)

Loan proportion for 0: 0.23847130164997885
Loan proportion for 1: 0.7615286983500211

Half_Yearly proprotion for 0: 0.26461038961038963
Half_Yearly proprotion for 1: 0.7353896103896104

Monthly proprotion for 0: 0.07816711590296496
Monthly proprotion for 1: 0.921832884097035

Quaterly proprotion for 0: 0.2944743935309973
Quaterly proprotion for 1: 0.7055256064690026


In [119]:
k = 1
f = 1

lamda_HY = 1 / (1 + np.exp(-(HY_total - k)/f))

In [122]:
lamda_HY

1.0